### ISSUE TITLE
Randomize First Player

### ISSUE THREAD

**Issue by teeks99** [PSU-SW500-SU16-T5/sinking-feeling#149]
Game should randomly pick which player gets to go first. Probably in checkStateSetup() near game.js:165

**Comment by nagledb** [comment]
I'd prefer to make it configurable. Let the creator choose whether the creator starts first, the opponent starts first, or whether it's randomly determined.

I added a first_player field (which checkStateSetup is checking), so that should get populated at creation (at the same time the user picks AI or human opponent, etc.).
